linters-settings:
  dupl:
    # Tokens count to trigger issue.
    # Default: 150
    threshold: 100
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - unused
    - dupl
issues:
run:
  timeout: 5m
  skip-dirs:
    - deploy
    - .vscode
