# Build Stage
FROM golang:1.21-alpine AS builder
WORKDIR /students-api
COPY go.mod go.sum ./
RUN go mod download
COPY . ./
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o students-api cmd/main.go

# Final Stage
FROM alpine:3.14
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /students-api/students-api .
EXPOSE 3000
CMD ["./students-api"]
