version: '3.8'

services:
  nodeapp:
    image: 6942fca36c5e
    command: sh -c 'VAL=$$HOSTNAME npm start'
    deploy:
      replicas: 3        

  nginx:
    image: nginx:latest
    environment:
      - NGINX_PORT=80
      - WEB_APP=nodeapp
      - WEB_PORT=3000
    ports:
      - 80:80
    volumes:
      - ./templates/default.conf.template:/etc/nginx/templates/default.conf.template
    depends_on:
      - nodeapp
